version: '3.8'

volumes:
  shadb_vol:
    driver: local

services:
  shadb:
    volumes:
      - shadb_vol:/var/lib/mysql
  shaservice:
    environment:
      DB_HOST: shadb
      PORT: ${RAILS_PORT}
      RAILS_ENV: 'development'
      RAILS_MASTER_KEY: '1234567890asdfasdfasdfasdfasdfas' 
    ports:
      - '${RAILS_PORT}:${RAILS_PORT}'
    tmpfs:
      - /opt/shaservice/tmp/pids/
