version: '3.3'

services:
  sha_service:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt/sha_service
    command: ["/bin/bash"]
    ports:
      - '3000:3000'
